connection_throttle: 4000
online_mode: true
remote_ping_timeout: 5000
groups:
  md_5:
  - admin
servers:
  lobby:
    address: lobby:30001
    motd: ''
    restricted: false
  danish-survival:
    address: danish-survival:30005
    motd: ''
    restricted: false
  cs-tmm:
    address: cs-tmm:30100
    motd: ''
    restricted: false
  creative:
    address: creative:30101
    motd: ''
    restricted: false
  parkour:
    address: parkour:30102
    motd: ''
    restricted: false
  test:
    address: test:30999
    motd: ''
    restricted: false
remote_ping_cache: -1
connection_throttle_limit: 3
enforce_secure_profile: false
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:25565
  max_players: 2025
  motd: ''
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: true
  query_port: 25565
  tab_list: GLOBAL_PING
  tab_size: 60
server_connect_timeout: 5000
player_limit: 2021
max_packets_per_second: 4096
ip_forward: true
disabled_commands:
- revertaddresses
log_pings: true
max_packets_data_per_second: 33554432
forge_support: false
log_commands: false
stats: eeff8c06-80b0-49a1-ab8c-697022039a24
reject_transfers: false
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
prevent_proxy_connections: false
timeout: 20000
