server_connect_timeout: 5000
enforce_secure_profile: false
forge_support: false
player_limit: 2021
log_pings: true
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
timeout: 20000
log_commands: false
network_compression_threshold: 256
online_mode: true
disabled_commands:
- revertaddresses
servers:
  lobby:
    address: mc.theflyingbirds.net:30001
    motd: ''
    restricted: false
  danish-survival:
    address: mc.theflyingbirds.net:30005
    motd: ''
    restricted: false
  cs-tmm:
    address: mc.theflyingbirds.net:30100
    motd: ''
    restricted: false
  creative:
    address: mc.theflyingbirds.net:30101
    motd: ''
    restricted: false
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:25565
  max_players: 2024
  motd: ''
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: true
  query_port: 25565
  tab_list: GLOBAL_PING
  tab_size: 60
ip_forward: true
remote_ping_timeout: 5000
reject_transfers: false
remote_ping_cache: -1
connection_throttle: 4000
stats: eeff8c06-80b0-49a1-ab8c-697022039a24
connection_throttle_limit: 3
groups:
  md_5:
  - admin
prevent_proxy_connections: false
