---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: tfb-servers
  annotations:
  #  "mc-router.itzg.me/externalServerName": "mc.theflyingbirds.net"
    metallb.universe.tf/allow-shared-ip: "mykey-65.108.8.46"
spec:
  type: LoadBalancer
  loadBalancerIP: 65.108.8.46
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
    - name: plan
      port: 8804
      targetPort: 8804
  selector:
    run: proxy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy
  namespace: tfb-servers
  labels:
    run: proxy
spec:
  serviceName: "proxy"
  replicas: 1
  selector:
    matchLabels:
      run: proxy
  template:
    metadata:
      labels:
        run: proxy
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: git-repo-volume
        emptyDir: {}
      - name: git-secret-volume
        secret:
          secretName: git-secret
          defaultMode: 256
      - name: gradle-credentials
        secret:
          secretName: gradle-credentials
      initContainers:
      - name: delete-old-jar-files
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["rm -rf /data/*.jar && rm -rf /data/plugins/*.jar"]
        volumeMounts:
        - name: proxy-pv
          mountPath: /data
      - name: git-sync
        image: k8s.gcr.io/git-sync-amd64:v2.0.6
        imagePullPolicy: Always
        volumeMounts:
        - name: git-repo-volume
          mountPath: /git-data
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/theflyingbirdsmc/TFB-Network.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/git-data"
        - name: GIT_SYNC_DEST
          value: "temp"
        - name: GIT_SYNC_PERMISSIONS
          value: "0777"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
      - name: move-files
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["cp -r /git-data/temp/proxy/* /server && rm -rf /git-data/temp"]
        volumeMounts:
        - name: git-repo-volume
          mountPath: /git-data
        - name: proxy-pv
          mountPath: /server
      - name: gradle-build
        image: gradle:latest
        volumeMounts:
        - name: proxy-pv
          mountPath: /server
        env:
        - name: MAVEN_URL
          value: "https://jfrog.theflyingbirds.net/artifactory"  # Set your Maven repository URL here
        - name: MAVEN_USERNAME
          valueFrom:
            secretKeyRef:
              name: gradle-credentials
              key: username
        - name: MAVEN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gradle-credentials
              key: token
        command: ["/bin/sh", "-c"]
        args: ["cd /server && gradle update -PmavenUrl=$MAVEN_URL -PmavenUsername=$MAVEN_USERNAME -PmavenPassword=$MAVEN_PASSWORD"]
      containers:
      - name: proxy
        image: itzg/bungeecord
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: BUNGEE_JAR_FILE
            value: "/server/server.jar"
        ports:
          - containerPort: 25565
        volumeMounts:
          - name: proxy-pv
            mountPath: /server
          - name: git-repo-volume
            mountPath: /git-data
        resources:
          requests:
            memory: "4Gi"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
          initialDelaySeconds: 120
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: proxy-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
