---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: tfb-servers
  annotations:
    backstage.io/kubernetes-id: proxy
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  labels:
    backstage.io/kubernetes-id: proxy
spec:
  type: LoadBalancer
  loadBalancerIP: 65.108.8.46
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
    - name: plan
      port: 8804
      targetPort: 8804
    - name: votifier
      port: 8192
      targetPort: 8192
  selector:
    run: proxy

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy
  namespace: tfb-servers
  labels:
    run: proxy
    backstage.io/kubernetes-id: proxy
spec:
  serviceName: "proxy"
  replicas: 1
  selector:
    matchLabels:
      run: proxy
  template:
    metadata:
      labels:
        run: proxy
        backstage.io/kubernetes-id: proxy
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: git-repo-volume
        emptyDir: {}
      - name: git-secret-volume
        secret:
          secretName: git-secret
          defaultMode: 256
      - name: gradle-credentials
        secret:
          secretName: gradle-credentials
      initContainers:
      - name: delete-old-jar-files
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["rm -rf /data/*.jar && rm -rf /data/plugins/*.jar"]
        volumeMounts:
        - name: proxy-pv
          mountPath: /data
      - name: git-sync
        image: k8s.gcr.io/git-sync-amd64:v2.0.6
        imagePullPolicy: Always
        volumeMounts:
        - name: git-repo-volume
          mountPath: /git-data
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/theflyingbirdsmc/proxy.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/git-data"
        - name: GIT_SYNC_DEST
          value: "temp"
        - name: GIT_SYNC_PERMISSIONS
          value: "0777"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
      - name: move-files
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["cp -r /git-data/temp/* /server && rm -rf /git-data/temp"]
        volumeMounts:
        - name: git-repo-volume
          mountPath: /git-data
        - name: proxy-pv
          mountPath: /server
      - name: gradle-build
        image: gradle:latest
        volumeMounts:
        - name: proxy-pv
          mountPath: /server
        env:
        - name: MAVEN_URL
          value: "https://jfrog.theflyingbirds.net/artifactory"  # Set your Maven repository URL here
        - name: MAVEN_USERNAME
          valueFrom:
            secretKeyRef:
              name: gradle-credentials
              key: username
        - name: MAVEN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gradle-credentials
              key: token
        command: ["/bin/sh", "-c"]
        args: ["cd /server && gradle update -PmavenUrl=$MAVEN_URL -PmavenUsername=$MAVEN_USERNAME -PmavenPassword=$MAVEN_PASSWORD"]
      containers:
      - name: proxy
        image: itzg/bungeecord:java21
        env:
          - name: TYPE
            value: "CUSTOM"
          - name: BUNGEE_JAR_FILE
            value: "/server/server.jar"
          - name: DEBIAN_FRONTEND
            value: noninteractive
        ports:
          - containerPort: 25565
          - containerPort: 8804
          - containerPort: 8192
        command: ["/bin/sh",]
        args: [ "-c", "apt-get update && apt-get install -y screen && screen -dmS minecraft /usr/bin/run-bungeecord.sh && tail -f /dev/null"]
        securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
        volumeMounts:
          - name: proxy-pv
            mountPath: /server
          - name: git-repo-volume
            mountPath: /git-data
        resources:
          requests:
            memory: "4Gi"
        readinessProbe:
          exec:
            command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          exec:
            command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
          initialDelaySeconds: 120
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: proxy-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tfb-network-db
  namespace: tfb-servers
spec:
  serviceName: "tfb-network-db"
  replicas: 1
  selector:
    matchLabels:
      app: tfb-network-db
  template:
    metadata:
      labels:
        app: tfb-network-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.1.2-jammy
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: tfb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/mariadb.conf.d/99-bind-address.cnf
          subPath: my.cnf
      volumes:
      - name: config-volume
        configMap:
          name: mariadb-config
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tfb-network-db
  namespace: tfb-servers
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: tfb-network-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: tfb-servers
data:
  my.cnf: |
    [mysqld]
    max_allowed_packet=16M
    max_connections=100000
    bind-address=*
    [Service]
    LimitNOFILE=10000000
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: tfb-servers
type: Opaque
data:
  root-password: RWF0TXlTaDBydHM=
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plan-ingress
  namespace: tfb-servers
  annotations:
    cert-manager.io/cluster-issuer: theflyingbirds-prod
spec:
  tls:
  - hosts:
    - stats.theflyingbirds.net
    secretName: plan-tls
  rules:
  - host: stats.theflyingbirds.net
    http:
      paths:
      - backend:
          service:
            name: proxy
            port:
              number: 8804
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votifier-ingress
  namespace: tfb-servers
  annotations:
    cert-manager.io/cluster-issuer: theflyingbirds-prod
spec:
  tls:
  - hosts:
    - mc.theflyingbirds.net
    secretName: votifier-tls
  rules:
  - host: mc.theflyingbirds.net
    http:
      paths:
      - backend:
          service:
            name: proxy
            port:
              number: 8192
        path: /
        pathType: Prefix